import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { redirect } from "next/navigation"
import QRCode from "qrcode"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { format } from "date-fns"

export default async function AttendancePage() {
  const session = await auth()
  if (!session?.user?.id) redirect("/login")

  const profile = await prisma.profile.findUnique({
    where: { userId: session.user.id },
    select: { usn: true, firstName: true, lastName: true, branch: true },
  })

  // Get all attendance records for this student (pre-generated by admin)
  const attendanceRecords = await prisma.attendance.findMany({
    where: { studentId: session.user.id },
    orderBy: { createdAt: "desc" },
  })

  // Enrich with job info
  const jobIds = [...new Set(attendanceRecords.map((a) => a.jobId).filter(Boolean))] as string[]
  const jobs = await prisma.job.findMany({
    where: { id: { in: jobIds } },
    select: { id: true, title: true, companyName: true },
  })
  const jobMap = Object.fromEntries(jobs.map((j) => [j.id, j]))

  // Generate QR data URLs server-side
  const recordsWithQr = await Promise.all(
    attendanceRecords.map(async (record) => {
      const qrDataUrl = await QRCode.toDataURL(record.qrCode, {
        width: 220,
        margin: 2,
        color: { dark: "#000000", light: "#ffffff" },
      })
      return { ...record, qrDataUrl, job: record.jobId ? jobMap[record.jobId] : null }
    })
  )

  const pending = recordsWithQr.filter((r) => !r.scannedAt)
  const attended = recordsWithQr.filter((r) => r.scannedAt)

  return (
    <main className="container mx-auto max-w-5xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-xl font-semibold tracking-tight">My Attendance QR Codes</h1>
        <p className="text-muted-foreground mt-1 text-sm">
          Show your QR code to the admin at each round to mark your attendance.
        </p>
      </div>

      {attendanceRecords.length === 0 && (
        <Card>
          <CardContent className="py-12 text-center text-muted-foreground">
            No attendance sessions have been created for you yet. Check back after the admin sets up the rounds.
          </CardContent>
        </Card>
      )}

      {pending.length > 0 && (
        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Upcoming / Pending</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {pending.map((record) => (
              <Card key={record.id} className="overflow-hidden">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between gap-2">
                    <div className="space-y-0.5">
                      <CardTitle className="text-base leading-tight">
                        {record.job?.companyName ?? "Company"}
                      </CardTitle>
                      <p className="text-xs text-muted-foreground">
                        {record.job?.title}
                      </p>
                    </div>
                    <Badge variant="outline" className="shrink-0 text-xs">
                      {record.round ?? "General"}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="flex flex-col items-center gap-3 pb-5">
                  {/* QR Code */}
                  <div className="rounded-lg border p-2 bg-white">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={record.qrDataUrl}
                      alt={`QR code for ${record.job?.companyName} ${record.round}`}
                      width={180}
                      height={180}
                    />
                  </div>
                  <div className="text-center space-y-0.5">
                    <p className="text-xs font-medium">{profile?.usn}</p>
                    <p className="text-xs text-muted-foreground">
                      {profile?.firstName} {profile?.lastName}
                    </p>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Created {format(record.createdAt, "dd MMM yyyy")}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {attended.length > 0 && (
        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Attended</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {attended.map((record) => (
              <Card key={record.id} className="overflow-hidden opacity-75">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between gap-2">
                    <div className="space-y-0.5">
                      <CardTitle className="text-base leading-tight">
                        {record.job?.companyName ?? "Company"}
                      </CardTitle>
                      <p className="text-xs text-muted-foreground">
                        {record.job?.title}
                      </p>
                    </div>
                    <Badge className="shrink-0 text-xs bg-green-100 text-green-800 border-green-200">
                      ✓ Attended
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="pb-5 space-y-1 text-sm">
                  <p className="font-medium">{record.round ?? "General"}</p>
                  <p className="text-xs text-muted-foreground">
                    Scanned: {record.scannedAt ? format(record.scannedAt, "dd MMM yyyy, hh:mm a") : "-"}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}
    </main>
  )
}
